import Head from "next/head";
import Image from "next/image";
// import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Hussain | Front-End Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="text-5xl text-center font-bold tracking-[3px]">
          Portfolio
        </h1>
      </main>
    </div>
  );
}
